name: eslint

on:
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    container: node:19
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: frontend/node_modules
        key: frontend-node-modules-${{ runner.os }}-${{ hashFiles('frontend/yarn.lock') }}
        restore-keys: |
          frontend-node-modules-${{ runner.os }}-
    - name: Check eslint
      working-directory: frontend
      run: |
        yarn
        yarn lint --max-warnings 0
